sudo: true
language: java
group: edge

services:
  - xvfb

before_install:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

install: travis_retry

notifications:
  slack:
    secure: N2waajxdsxS72W4zwrahdtFGH2UZUTboL+RXXy8fmOizD4cm19C8BuSgBWmlxG/EgE1dctrG1sW+jhtPV8t0Jnxi/kdfPLFaB1sqJUJfnP32/0KSgwaH/YpGrphjgY/bZl//pKVpA1THapv0+rBO9+bwcCV0oBmFGDJRZi9dQbJ6qoAGLv1T3EVXzt1Rn+Woh+fl5o8C/Sq5pBHCVWp1ruJxYXAyhSbjcxNTsWvQ9wK1rdBKXrOtyAZjLtFQHCnPfyN3em7zyG6IyQQDUoLxkpuqruKzns9x4U00XuiluQcAIruCgyrO4/4N1wP4wYaE66OLpSnqKVKpOFq8M0kbO+RCdxH5unV6G+G3IYCbaVv0gskcEE00N2eEmZ/YVKND2nPmDfz6yF+WmCXKi8kpZybSxWR6UKd4lwEf27lI1F3SVvMk7xsfVFD487YtJ0v+xCA6Tsv2IjWoCrPtUdzd6Kz7ebomNhefhdhtTVMBJQf7lHHpI6C+2+EMUqGJUBYdD80JJ7vOb4xGFikil3yv7FH9YTstb14FnxaNrZtDrr4kEjCx3P81FkQYVvW+MGF+XtUnhT26rPOE/8qN4CDo1ZnmS2WrICoGRUdz8atlIvLVrfalLTb8Caa/9FLPhjYQunHvdem5PH3VRi7aeSktaKSUlOCeTi7F7D7sxIxBsQ0=
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"

matrix:
# **** INCLUDE ****
  include:
# integrationtests
  - jdk: openjdk11
    env: TRAVIS_RETRY=travis_retry BUILDCMD=integrationtests-wizard.sh DISPLAY=:99.0
  - jdk: openjdk11
    env: BUILDCMD=integrationtests-xtend-examples.sh DISPLAY=:99.0
  - jdk: openjdk11
    env: BUILDCMD=integrationtests-xtext-examples.sh DISPLAY=:99.0
# Java 11
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.16.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.16.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.17-J11.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.17-J11.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.17-J11.sh DISPLAY=:99.0
  # Build with Java 11 against Java 8 targets
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.18.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.18.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.18.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.19.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.19.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.19.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.20.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.20.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.20.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.21.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.21.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.21.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.22.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.22.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.22.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.23.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.23.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.23.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.24.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.24.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.24.sh DISPLAY=:99.0
  # Build with Java 11 against Java 11 targets
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.18-J11.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.18-J11.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.18-J11.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.19-J11.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.19-J11.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.19-J11.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.20-J11.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.20-J11.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.20-J11.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.21-J11.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.21-J11.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.21-J11.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.22-J11.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.22-J11.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.22-J11.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.23-J11.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.23-J11.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.23-J11.sh DISPLAY=:99.0
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.24-J11.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.24-J11.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.24-J11.sh DISPLAY=:99.0
# Java 11 "Oracle JDK"
#  - env: JDK='Oracle JDK 11' BUILDCMD=greetings-gradle-2.14.sh
#    install: . ./install-jdk.sh -F 11 -L BCL
# Java 8
  - jdk: openjdk8
    env: BUILDCMD=greetings-gradle-2.12.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-gradle-2.14.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-gradle-2.15.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-gradle-2.16.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-gradle-2.17.M1.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-gradle-2.17.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-gradle-2.18.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-gradle-2.19.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-gradle-2.20.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-gradle-2.21.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-gradle-2.22.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-gradle-2.23.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-gradle-2.24.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-maven-2.12.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-maven-2.13.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-maven-2.14.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-maven-2.15.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-maven-2.16.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-maven-2.17.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-maven-2.18.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-maven-2.19.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-maven-2.20.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-maven-2.21.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-maven-2.22.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-maven-2.23.sh
  - jdk: openjdk8 
    env: BUILDCMD=greetings-maven-2.24.sh
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.15.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0 TP=luna-linux
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0 TP=mars-linux
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0 TP=oxygen
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.15.sh DISPLAY=:99.0 TP=oxygen
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0 TP=oxygen
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0 TP=photon
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.15.sh DISPLAY=:99.0 TP=photon
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0 TP=photon
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0 TP=latest
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.17.sh DISPLAY=:99.0 TP=latest
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.18.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.19.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.20.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.21.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.22.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=greetings-tycho-2.23.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=domainmodel-2.15.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=domainmodel-2.16.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=domainmodel-2.17.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=domainmodel-2.18.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=domainmodel-2.19.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=domainmodel-2.20.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=domainmodel-2.21.sh DISPLAY=:99.0
  - jdk: openjdk8
    env: BUILDCMD=domainmodel-2.22.sh DISPLAY=:99.0
  - jdk: openjdk11
    env: BUILDCMD=domainmodel-2.23.sh DISPLAY=:99.0
  - jdk: openjdk11
    env: BUILDCMD=domainmodel-2.24.sh DISPLAY=:99.0
# The following environments are known to fail
#  allow_failures:
#  - env: JDK='Oracle JDK 11'
script:
- set -e
- $TRAVIS_RETRY sh -e scripts/$BUILDCMD
