/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import org.eclipse.xtext.ide.editor.contentassist.IPrefixMatcher;
import org.eclipse.xtext.ide.editor.contentassist.IProposalConflictHelper;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;

import com.google.inject.Binder;

/**
 * Use this class to register ide components.
 */
public class MyDslIdeModule extends AbstractMyDslIdeModule {

	@Override
	public void configureContentAssistLexer(Binder binder) {
		super.configureContentAssistLexer(binder);
	}

	@Override
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return super.bindIContentAssistParser();
	}

	@Override
	public Class<? extends IProposalConflictHelper> bindIProposalConflictHelper() {
		return super.bindIProposalConflictHelper();
	}

	@Override
	public Class<? extends IPrefixMatcher> bindIPrefixMatcher() {
		return super.bindIPrefixMatcher();
	}

	@Override
	public void configureExecutorService(Binder binder) {
		super.configureExecutorService(binder);
	}
	
}
