name: Build Latest

on: 
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

jobs:
  build_Gralde_J8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: scripts/greetings-gradle-2.24.sh
  build_Maven_J8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: scripts/greetings-maven-2.24.sh
  build_tycho_J8_on_J11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: scripts/greetings-tycho-2.24.sh
  build_tycho_J11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: scripts/greetings-tycho-2.24-J11.sh
  build_domain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: scripts/domainmodel-2.24.sh
  build_integ_wizard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: scripts/integrationtests-wizard.sh
  build_integ_xtend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: scripts/integrationtests-xtend-examples.sh
  build_integ_xtext:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: scripts/integrationtests-xtext-examples.sh

